name: Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node.js
      uses: actions/setup-node@v2
    - name: npm install, compile, test, lint
      run: |
        npm install
        npm test
        npm run lint
