#!/bin/bash

git config --global user.name "hyperchessbot"
git config --global user.email "hyperchessbot@gmail.com"
git config --global credential.helper store

cp s/config .git/config

git add . -A

git commit -m "$*"

git push github master

git push gitlab master
